name: 'php-active-releases-action'
description: 'This action retrieves a list of active PHP Releases'
author: 'Flavio Heleno <flaviohbatista@gmail.com>'

branding:
  icon: 'activity'
  color: 'black'

outputs:
  major:
    description: The list of major versions available, as a list of strings (string[])
  minor:
    description: The list of minor versions available, as a list of strings (string[])
  patch:
    description: The list of patch versions available, as a list of strings (string[])
  release:
    description: The list of releases available, as a list of objects (object[])

runs:
  using: 'docker'
  image: 'docker://ghcr.io/flavioheleno/php-active-releases-action:latest'
