name: Publish Package
on:
  release:
    types:
      - created
  workflow_dispatch:
    inputs:
      tag:
        description: Tag name
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout release
        if: github.event_name != 'workflow_dispatch'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Checkout tag
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: ${{ github.event.inputs.tag }}

      # githun.ref_name does not update (main -> {tag-name}) after checkout (used by workflow_dispatch)
      - name: Resolve tag name
        id: tag_name
        run: |
          echo "tag_name=$(git log -n1 --pretty="format:%d" | sed "s/, /\n/g" | grep tag: | sed "s/tag: \|)//g")" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          push: true
          build-args:
            "VERSION=${{ steps.tag_name.outputs.tag_name }}"
          tags: |
            ghcr.io/flavioheleno/php-active-releases-action:${{ steps.tag_name.outputs.tag_name }}
            ghcr.io/flavioheleno/php-active-releases-action:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
