name: shellcheck
permissions: {}
on:
  pull_request:
    paths:
      - '*.sh'
  push:
    branches:
      - main
    paths:
      - '*.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # v2.0.0
