name: shellcheck
permissions: {}
on:
  pull_request:
    paths:
      - '*.sh'
  push:
    branches:
      - main
    paths:
      - '*.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # v2.0.0
