name: yamllint
permissions: {}
on:
  pull_request:
    paths:
      - '*.yml'
      - '*.yaml'
  push:
    branches:
      - main
    paths:
      - '*.yml'
      - '*.yaml'

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Run yamllint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
